services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    env_file:
      - .env
    networks:
      - api
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: src/
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock
        - action: sync+restart
          path: compose-dev.yml
          target: api, db
        - action: rebuild
          path: .env
    image: jstockley/api:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - api
    ports:
      - "5001:5000"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5000/health-check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  api:
    name: api
