version: '3.6'
services:
  api:
    container_name: "jnstockley-api"
    image: jnstockley/api:v0.0.1
    working_dir: /opt/jstockley-api
    env_file:
      - .env
    restart: always
    networks:
      - "jnstockley-api"

networks:
  jnstockley-api:
    external: true
    name: "jnstockley-api"