version: '3.6'
services:
  api:
    image: jnstockley/api:v0.0.1
    working_dir: /opt/jstockley-api
    env_file:
      - .env
    restart: always
    networks:
      - "api"

networks:
  api:
    external: true
    name: "api"