---
name: Sync from Python Starter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # optional: runs daily at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: sync
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: 'dev'
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
  
      - name: Fetch external repo and create sync branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add external https://github.com/jnstockley/python-starter.git
          git fetch external main
          # Merge external main into current branch, overwriting conflicts
          git merge external/main --allow-unrelated-histories
          git checkout external/main -- .
          git add .
          # Commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Pull changes from python-starter"
          else
            echo "No changes to commit"
          fi

      - name: Create Pull Request if differences exist
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: dev
          title: "Sync from python-starter"
          body: |
            This PR syncs changes from [jnstockley/python-starter](https://github.com/jnstockley/python-starter).
          branch: sync
          delete-branch: false
