name: Run PyTests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - .github/workflows/**
      - poetry.lock
      - pyproject.toml

jobs:
  tests:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Step 3 - Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root --with test
      - name: Step 4 - Run Tests
        run: |
          export api_key=${{ secrets.API_KEY }}
          export PYTHONPATH=src:$PYTHONPATH
          poetry run pytest test
