name: Run PyTests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - .github/workflows/**
      - poetry.lock
      - pyproject.toml

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Step 3 - Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root --with test
      - name: Step 4 - Lint
        run: |
          poetry run black src/ --check
          poetry run black test/ --check
          poetry run isort src/ --check
          poetry run isort test/ --check

  tests:
    needs:
      - lint
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Step 3 - Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root --with test
      - name: Step 4 - Run Tests
        run: |
          export api_key=${{ secrets.API_KEY }}
          export PYTHONPATH=src:$PYTHONPATH
          poetry run pytest --cov=./ --cov-report=xml test
      - name: Step 5 - Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          slug: jnstockley/api
          files: ./coverage.xml