name: Run PyTests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - .github/workflows/**
      - poetry.lock
      - pyproject.toml

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Step 3 - Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root --with test
      - name: Step 4 - Lint
        run: |
          poetry run black src/ --check
          poetry run black test/ --check
          poetry run isort src/ --check
          poetry run isort test/ --check

  tests:
    needs:
      - lint
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Step 3 - Install Poetry and Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root --with test
      - name: Step 4 - Run Tests
        run: |
          export api_key=${{ secrets.API_KEY }}
          export PYTHONPATH=src:$PYTHONPATH
          poetry run pytest --cov=./ --cov-report=xml test
      - name: Step 5 - Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          slug: jnstockley/api
          files: ./coverage.xml

  push_to_registries:
    needs:
      - lint
      - tests
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            jnstockley/api
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jnstockley/api:testing
